Models/Provider.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace TherapistDatabase.Models
{
    public enum GenderCategories {
        [DisplayAttribute(Name = "Male")]
        Male,
        [DisplayAttribute(Name = "Female")]
        Female,
        [DisplayAttribute(Name = "Nonbinary")]
        Nonbinary 
    };

    public enum SpecialtyCategories
    {
        [DisplayAttribute(Name = "Child and Family")]
        Child,  // "Child and Family"
        [DisplayAttribute(Name = "Trauma and PTSD")]
        Trauma, // "Trauma and PTSD"
        [DisplayAttribute(Name = "Substance-Use Disorders")]
        Drug,   // "Substance-Use Disorders"
        [DisplayAttribute(Name = "Depression and Anxiety")]
        Dep,    // "Depression and Anxiety"
        [DisplayAttribute(Name = "ADHD, ADD, and Related")]
        ADHD,
        [DisplayAttribute(Name = "Personality Disorders")]
        Pers,   // "Personality Disorders"
        Other   // "Other"
    };

    public class Provider
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
       
        public SpecialtyCategories? Specialties { get; set; }  

        public int Age { get; set; }
        public GenderCategories? Gender { get; set; }
        public string PhotoPath { get; set; }
               
        public Provider()
        {
            FirstName = "Unknown";
            LastName = "Unknown";
            PhotoPath = "";
        }
    }
}

Controllers/ProviderController.cs
using Microsoft.AspNetCore.Mvc;
using TherapistDatabase.Models;
using System.Web;
using System.Net.Http.Headers;

namespace TherapistDatabase.Controllers
{
    public class ProviderController : Controller
    {
        private readonly IProviderRepository repo;

        public ProviderController(IProviderRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index() => View(repo.GetAllProviders());

        public IActionResult AddProvider() => View(new Provider());

        public IActionResult ViewProvider(int id)
        {
            var provider = repo.GetProvider(id);
            if(provider == null) return View("ProviderNotFound");
            return View(provider);
        }
                
        public IActionResult AddProviderToDatabase(Provider p, List<IFormFile> files)
        {
            
            /* TODO: Add checking for file size, remove the stuff about multiple files, check if img is already in images directory before
             *       copying, etc.  Same on UpdateProviderToDatabase below.
             */
            long size = files.Sum(f => f.Length);
            var filePaths = new List<string>();
            foreach(var formFile in files) {
                if(formFile.Length > 0) {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", formFile.FileName);
                    filePaths.Add(filePath);
                    using(var stream = new FileStream(filePath, FileMode.Create)) {
                        formFile.CopyTo(stream);                         //copy file to images directory using windows conventions
                        p.PhotoPath = $"~/images/{formFile.FileName}";   //send file path info to db--stored with unix notation for display via html
                    }

                }
            }

            repo.AddProvider(p);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteProvider(int id)
        {
            repo.DeleteProvider(id);
            return RedirectToAction("Index");
        }

        public IActionResult UpdateProvider(int id)
        {
            var p = repo.GetProvider(id);
            if(p == null) return View("ProviderNotFound");
            return View(p);
        }

        public IActionResult UpdateProviderToDatabase(Provider p, List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);
            var filePaths = new List<string>();
            foreach(var formFile in files) {
                if(formFile.Length > 0) {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", formFile.FileName);
                    filePaths.Add(filePath);
                    using(var stream = new FileStream(filePath, FileMode.Create)) {
                        formFile.CopyTo(stream);                        //copy file to images directory using windows conventions
                        p.PhotoPath = $"~/images/{formFile.FileName}";   //send file path info to db--stored with unix notation for display via html
                    }

                }
            }
            repo.UpdateProvider(p);
            return RedirectToAction("ViewProvider", new { id = p.EmployeeID });
        }
    }
}

Views/Provider/AddProvider.cshtml
@model Provider

<h3>To add a provider to the provider database, please enter the following information.</h3>
<h4>(Note that an employee ID will be automatically generated for the provider.)</h4>

@using(Html.BeginForm("AddProviderToDatabase", "Provider", FormMethod.Post, new { enctype = "multipart/form-data" } )) {
   
        @*  TODO: Possibly allow user to specify an employee ID #. 
            <label asp-for="EmployeeID" class="control-label">Employee ID</label>
            <input type="number" name="EmployeeID" class="form-control" value="@Model.EmployeeID" />
        *@
  
        
            <div class="form-group row">
                <div class="form-group col">
                    <label asp-for="FirstName" class="control-label">First Name:</label>
                    <input type="text" autofocus required name="FirstName" class="form-control" placeholder="First name required" />
                </div>
                <div class="form-group col">
                    <label asp-for="LastName" class="control-label">Last Name:</label>
                    <input type="text" required name="LastName" class="form-control" placeholder="Last name required" />
                </div>
            </div>
   
            <div class="form-group row">
                <div class="form-group col">
                    <label asp-for="Gender" class="control-label">Gender:</label>
                    <select asp-for="Gender" asp-items="Html.GetEnumSelectList<GenderCategories>()" class="form-control" name="Gender" >
                        <option value="" disabled selected hidden>Click to select</option>
                    </select>
                </div>
                <div class="form-group col">
                    <label asp-for="Age" class="control-label">Age:</label>
                    <input type="number" step="1" name="Age" class="form-control" value="0" />
                </div>

            </div>

        @* TODO: Make a multi-select form for specialties.  Something like:
       <label asp-for="Specialties" class="control-label">Select one or more specialties for this provider:</label>
        <select asp-for="Specialties" asp-items="TherapistDatabase.Models.SpecialtyListModel.Specialties"></select>*@

            <div class="form-group row">
                <div class="form-group col">
                    <label asp-for="Specialties" class="control-label">Specialty Area:</label>
                    <select asp-for="Specialties" asp-items="Html.GetEnumSelectList<SpecialtyCategories>()" class="form-control" name="Specialties" >
                        <option value="" disabled selected hidden>Click to select</option>
                    </select>
                </div>
            </div>
     
            <div class="form-group row">
                <div class="form-group col">
                    <label for="image_upload" class="form-label">Upload Provider Photo:</label>
                    <input class="form-control" type="file" name="files" id="image_upload" multiple />
                </div>
                <div class="form-group col">
                    <img src="" asp-append-version="true" id="provider_photo"
                     class="provider_photo" alt="Photo of Provider"
                     hidden="true" />
                </div>
            </div>
  

    
    <div class="form row justify-content-center">
        <input type="submit" value="Add Provider" id="add_prov_btn" class="btn" />
    </div>
    }
    



<script>   // Un-hide image display when user selects image, and verify img file is valid file type:

   const fileTypes = [
        "image/apng",
        "image/bmp",
        "image/gif",
        "image/jpeg",
        "image/pjpeg",
        "image/png",
        "image/svg+xml",
        "image/tiff",
        "image/webp",
        "image/x-icon"
    ];
    function validFileType(file) { return fileTypes.includes(file.type); }

    const image_upload = document.getElementById("image_upload");

    image_upload.addEventListener("change", e => {
        const file = image_upload.files[0];
        if (!validFileType(file)) { window.alert("Invalid file type."); }
        else {
            document.getElementById('provider_photo').src = URL.createObjectURL(file);
            document.getElementById('provider_photo').hidden=false;
        }
    });

</script>

Views/Provider/Index.cshtml
@model IEnumerable<Provider>
@{
    ViewData["Title"] = "Provider Database";
}

<h2>Provider List</h2>
<h3>Click on an employee number to make an appointment.</h3>

<table class="table table-hover">

    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Specialties</th>
        <th>Age</th>
        <th>Gender</th>
        @*<th>Availability?</th>*@
    </tr>

    @foreach(var p in Model) {
    <tr>
      
        <td><a href=/Provider/ViewProvider/@p.EmployeeID>@p.EmployeeID</a></td>
        <td>@p.FirstName</td>
        <td>@p.LastName</td>
        @switch(p.Specialties) {
                case SpecialtyCategories.Drug: <td>Substance-Use Disorders</td>; break;
                case SpecialtyCategories.Pers: <td>Personality Disorders</td>; break;
                case SpecialtyCategories.Child: <td>Child and Family</td>; break;
                case SpecialtyCategories.Trauma: <td>Trauma and PTSD</td>; break;
                case SpecialtyCategories.Dep: <td>Depression and Anxiety</td>; break;
                case SpecialtyCategories.ADHD: <td>ADHD, ADD, and Related</td>; break;
                case SpecialtyCategories.Other: <td>Other</td>; break;
                default: <td>None</td>; break;
            }
        <td>@p.Age</td>
        <td>@p.Gender</td>
    </tr>
    }

</table>

Views/Provider/UpdateProvider.cshtml
@model Provider

<h3>To update provider @Model.FirstName @Model.LastName, please enter the following information.</h3>

@using(Html.BeginForm("UpdateProviderToDatabase", "Provider", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    <input asp-for="EmployeeID" type="hidden" value="@Model.EmployeeID" />
   
    <div class="form-group row">
        <div class="form-group col">
            <label asp-for="FirstName" class="control-label">First Name</label>
            <input type="text" name="FirstName" class="form-control" value="@Model.FirstName" required />
        </div>    
        <div class="form-group col">
            <label asp-for="LastName" class="control-label">Last Name</label>
            <input type="text" name="LastName" class="form-control" value="@Model.LastName" required />
        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col">
            <label asp-for="Age" class="control-label">Age</label>
            <input type="number" step="1" name="Age" class="form-control" value="@Model.Age" />         
        </div>
        <div class="form-group col">
            <label asp-for="Gender" class="control-label">Gender:</label>
            <select asp-for="Gender" asp-items="Html.GetEnumSelectList<GenderCategories>()" class="control-label" value="@Model.Gender" name="Gender">Gender:</select>

        </div>
    </div>

    <div class="form-group row">
        <div class="form-group col">
            <label asp-for="Specialties" class="control-label">Select Specialty for this Provider:</label>
            <select asp-for="Specialties" asp-items="Html.GetEnumSelectList<SpecialtyCategories>()" class="control-label" name="Specialties"></select>
         </div>
    </div>
   
    <br />

    <div class="form-group row">
        <div class="form-group col">
            <label for="image_upload" class="form-label">Change Provider Photo:</label>
            <input class="form-control" id="image_upload" type="file" name="files" multiple>
        </div>
        <div class="form-group col">
             <img src=@Model.PhotoPath asp-append-version="true" id="provider_photo"
             class="provider_photo" alt="Photo of Provider"/>
        </div>
    </div>

    <div class="form row justify-content-center">
        <input type="submit" value="Update Provider" id="update_prov_btn" class="btn" />
    </div>
}


<script>
    const fileTypes = [
        "image/apng",
        "image/bmp",
        "image/gif",
        "image/jpeg",
        "image/pjpeg",
        "image/png",
        "image/svg+xml",
        "image/tiff",
        "image/webp",
        "image/x-icon"
    ];
    function validFileType(file) { return fileTypes.includes(file.type); }

    const image_upload = document.getElementById("image_upload");

    image_upload.addEventListener("change", e => {
        const file = image_upload.files[0];
        if (!validFileType(file)) { window.alert("Invalid file type."); }
        else {
            document.getElementById('provider_photo').src = URL.createObjectURL(file);
        }
    });

</script>

@*<script>
   /*Using FETCH API:*/
  
   const fileTypes = [
        "image/apng",
        "image/bmp",
        "image/gif",
        "image/jpeg",
        "image/pjpeg",
        "image/png",
        "image/svg+xml",
        "image/tiff",
        "image/webp",
        "image/x-icon"
    ];
   function validFileType(file) { return fileTypes.includes(file.type); }
  
   const image_upload=document.getElementById("image_upload");

   image_upload.addEventListener("change", e => {
        const file = image_upload.files[0];
        if (!validFileType(file)) { window.alert("Invalid file type."); }
        else {
            document.getElementById('provider_photo').src = URL.createObjectURL(file);
        }
    });

   image_upload.addEventListener("submit", e => {
       e.preventDefault();
       
       const endpoint="";
       const formData=new FormData(); //holds files

       console.log(image_upload.files);

       formData.append("image_upload",image_upload.files[0]);

       fetch(endpoint,{
           method: "post",
           body: formData
       }).catch(console.error);
   });
   
</script>*@

Views/Provider/ViewProvider.cshtml
@model Provider


<div class="prov_title">Information for provider: @Model.FirstName @Model.LastName</div>


<form>
    <div class="form row justify-content-center">
    <input type="submit" value="Update Provider" id="up_prov_btn" class="btn" formaction="/Provider/UpdateProvider/@Model.EmployeeID" />
    <input type="submit" value="Delete Provider" id="del_prov_btn" class="btn" formaction="/Provider/DeleteProvider/@Model.EmployeeID" 
           onclick="return confirm('Deleting a provider cannot be undone.  Are you sure you want to delete this provider?')" />
    </div>
 </form>

<div class="row justify-content-center">
    <div class="col-auto mr-auto">
        <img src=@Model.PhotoPath asp-append-version="true"  id="provider_photo" class="provider_photo" alt="Photo of Provider" />
    </div>
    <div class="col-auto ml-auto">
        <div class="single_provider_table">
        <table class="table table-hover">
            <tr>
                <td>Employee ID:</td>
                <td>@Model.EmployeeID</td>
            </tr>
            <tr>
                <td>First Name:</td>
                <td>@Model.FirstName</td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td>@Model.LastName</td>
            </tr>
            <tr>
                <td>Specialties:</td>
                @switch(Model.Specialties) {
                    case SpecialtyCategories.Drug: <td>Substance-Use Disorders</td>; break;
                    case SpecialtyCategories.Pers: <td>Personality Disorders</td>; break;
                    case SpecialtyCategories.Child: <td>Child and Family</td>; break;
                    case SpecialtyCategories.Trauma: <td>Trauma and PTSD</td>; break;
                    case SpecialtyCategories.Dep: <td>Depression and Anxiety</td>; break;
                    case SpecialtyCategories.ADHD: <td>ADHD, ADD, and Related</td>; break;
                    case SpecialtyCategories.Other: <td>Other</td>; break;
                    default: <td>None</td>; break;
                }
            </tr>
            <tr>
                <td>Age:</td>
                <td>@Model.Age</td>
            </tr>
            <tr>
                <td>Gender:</td>
                <td>@Model.Gender</td>
            </tr>
        </table>
        </div>
    </div>
</div>

@* ********************* *@
@*     Calendly API:     *@
@* ********************* *@
<div class="scheduling_container">
    <link href="https://calendly.com/assets/external/widget.css" rel="stylesheet">
    <script src="https://calendly.com/assets/external/widget.js" type="text/javascript"></script>
    <div class="form row justify-content-center">
        <button class="btn" onclick="" disabled="disabled">View Schedule</button>

        @*     TODO: Display scheduling info for individual provider,
         *           including upcoming available appts.  See
         *           https://developer.calendly.com/api-docs/6a1be82aef359-list-event-type-available-times
         *           for implementation details.
         *@
        <button class="btn" onclick="Calendly.showPopupWidget('https://calendly.com/providerbase/therapy'); return false;">Make Appointment</button>
    </div>
</div>